# -*- coding: utf-8 -*-
"""Women safety in India.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aKfecb8aTl2dzAYh62R8CZAHE5r4N1j1
"""

from google.colab import files
uploaded = files.upload()

import io
import pandas as pd


crimes_df = pd.read_csv(io.BytesIO(uploaded['crimes_against_women_2001-2014.csv']))

crimes_df

crimes_df.shape

"""**Data Preparation and Cleaning**
To start with the very basic of data cleaning, let's find out if any of the columns have any Null or missing values

"""

overall_crime = crimes_df.isna().sum()
overall_crime

districts = len(crimes_df.DISTRICT.unique())
districts

crimes_df.drop(['DISTRICT', 'Unnamed: 0'], axis = 1, inplace=True)
crimes_df.rename( columns = {'Kidnapping and Abduction':'Kidnapping_Abduction','Dowry Deaths':'Dowry_Deaths',
                             'Assault on women with intent to outrage her modesty':'Hurting_of_womens_modesty',
                             'Insult to modesty of Women':'Insult_to_womens_modesty',
                             'Cruelty by Husband or his Relatives':'Domestic_Cruelty',
                             'Importation of Girls':'Importation_of_Girls'}, inplace = True)
crimes_df

print(crimes_df['STATE/UT'].unique())

def remove_uppercase(r):
    r = r['STATE/UT'].strip()
    r = r.upper()
    return r
crimes_df['STATE/UT'] = crimes_df.apply(remove_uppercase, axis=1)

#Now use replace function to replace the other type of repeated datas as dicussed above
crimes_df['STATE/UT'].replace("A&N ISLANDS", "A & N ISLANDS", inplace = True)
crimes_df['STATE/UT'].replace("D&N HAVELI", "D & N HAVELI", inplace = True)
crimes_df['STATE/UT'].replace("DELHI UT", "DELHI", inplace = True)

crimes_df['STATE/UT'].unique()



"""**Now check the total number of States+UT**"""

len(crimes_df['STATE/UT'].unique())

"""**Exploratory Analysis and Visualization**

Let us find out the total population of women over the years, 2001-2014, who has been a victim of the crime based on their gender.
"""

victims_raped = crimes_df.Rape.sum()
victims_kidnapped_abducted = crimes_df.Kidnapping_Abduction.sum()
dowery_death = crimes_df.Dowry_Deaths.sum()
modesty_assault = crimes_df.Hurting_of_womens_modesty.sum()
insult_to_modesty = crimes_df.Insult_to_womens_modesty.sum()
domestic_violence = crimes_df.Domestic_Cruelty.sum()
girls_imported = crimes_df.Importation_of_Girls.sum()

total_population_of_victim_overall = victims_raped + victims_raped + dowery_death +modesty_assault+ insult_to_modesty + domestic_violence+ girls_imported
total_population_of_victim_overall

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

fig, axes = plt.subplots(2, 3, figsize=(25, 12))

axes[0,0].set_title("Chart of rape cases in India in 2001-2014")
axes[0,0].bar(crimes_df.Year, crimes_df.Rape, color = 'black');
plt.xlabel('Year') #X-axis
plt.ylabel('Cases of Rape in India') #Y-axis

axes[0,1].set_title("Chart of Kidnapping and Abduction cases in India in 2001-2014")
axes[0,1].bar(crimes_df.Year, crimes_df.Kidnapping_Abduction, color = 'violet');
plt.xlabel('Year') #X-axis
plt.ylabel('Cases of Kidnapping and Abduction in India') #Y-axis

axes[0,2].set_title("Chart of Dowry death cases in India in 2001-2014")
axes[0,2].bar(crimes_df.Year, crimes_df.Dowry_Deaths, color = 'navy');
plt.xlabel('Year') #X-axis
plt.ylabel('Cases of Dowry deaths in India') #Y-axis

axes[1,0].set_title("Chart of Assault to her modesty in 2001-2014")
axes[1,0].bar(crimes_df.Year, crimes_df.Hurting_of_womens_modesty, color = 'cyan');
plt.xlabel('Year') #X-axis
plt.ylabel('Cases of Assaulting a women for her modesty in India') #Y-axis

axes[1,1].set_title("Chart of Domestic Violence cases in India in 2001-2014")
axes[1,1].bar(crimes_df.Year, crimes_df.Domestic_Cruelty, color = 'orange');
plt.xlabel('Year') #X-axis
plt.ylabel('Cases of Domestic Violence in India') #Y-axis

axes[1,2].set_title("Chart of Importation of girls in India in 2001-2014")
axes[1,2].bar(crimes_df.Year, crimes_df.Importation_of_Girls, color = 'red');
plt.xlabel('Year') #X-axis
plt.ylabel('Cases ofImportation of girls in India') #Y-axis



"""**There are two things to be concluded from the above bar chart -**
1) The cases have incraesed over the years.
2) 2014 has been the year, where violance against women was reported the maximum, under each of the cases like, rape, domestic violence etc, which can also be proved below, which can also be cross examined with the code below.
"""

count_df = crimes_df.groupby('Year')[['STATE/UT']].count()
count_df

"""# Let us use seaborn to take help of heatmap to represent how more cases from each state started coming up more frequently with each passing year."""

plt.figure(figsize=(10,5))
plt.title("Total cases reported from every state Year wise")
sns.heatmap(count_df);

"""**Crime is increasing with year**

# **Conclusion and Analysis **
"""

crimes_df = crimes_df.drop(['Hurting_of_womens_modesty', 'Insult_to_womens_modesty'], axis=1)

"""**Q . Create a dataframe containing 10 highest reported rape cases in India, in the span of year 2001-2014.**"""

max_rape_cases = crimes_df.sort_values('Rape', ascending = False).head(10)
max_rape_cases

"""**Q. Create a dataframe containing 10 highest reported Domestic Violance cases in India, in the span of year 2001-2014.**"""

max_domestic_violance_cases = crimes_df.sort_values('Domestic_Cruelty', ascending = False).head(10)
max_domestic_violance_cases

"""*Q. Create a dataframe containing 10 highest reported Importation cases in India, in the span of year 2001-2014.**"""

max_importation_case = crimes_df.sort_values('Importation_of_Girls', ascending = False).head(10)
max_importation_case

"""**Q. Find out the total number of cases, in span of 2001-2014 under each category, state wise.**"""

counts_df = crimes_df.groupby('STATE/UT')[['Rape', 'Kidnapping_Abduction', 'Dowry_Deaths','Domestic_Cruelty', 'Importation_of_Girls']].sum()
counts_df

"""**Q. Find out the top 5 states, where maximum numbers of cases has been reported in TOTAL in span of 2001-2014, each category wise.**

For "Rape" case -
"""

counts_df.sort_values(by = 'Rape', ascending = False).head(5)

"""For Kidnapping and abduction case -"""

counts_df.sort_values(by = 'Kidnapping_Abduction', ascending = False).head(5)

"""For cases of deaths due to dowry -"""

counts_df.sort_values(by = 'Dowry_Deaths', ascending = False).head(5)

"""For Domestic Violance case -"""

counts_df.sort_values(by = 'Domestic_Cruelty', ascending = False).head(5)

"""For Importation of Girls case -

"""

counts_df.sort_values(by = 'Importation_of_Girls', ascending = False).head(5)

"""**Q: Which state has featured in both the lists of "Maximum number of rape cases" and "Maximum number of Importation cases"**"""

max_importation_case = max_importation_case.merge(max_rape_cases)
max_importation_case

"""**Q: Which state has featured in both the lists of "Maximum number of rape cases" and "Maximum number of Deaths due to Domestic violance cases".**"""

max_domestic_death_case = max_domestic_violance_cases.merge(max_rape_cases)
max_domestic_violance_cases